### ISSUE TITLE
Freemarker não está sendo carregado corretamente

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/biblivre#111]
1. Inicie o Biblivre 5 Cloud
2. Faça uma pesquisa bibliográfica

A seguinte exceção pode ser vista nos logs:

```
java.io.FileNotFoundException: WebContent/freemarker does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:122)
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:119)
	at java.security.AccessController.doPrivileged(Native Method)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:119)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:98)
	at freemarker.template.Configuration.setDirectoryForTemplateLoading(Configuration.java:1539)
	at biblivre.circulation.lending.LendingBO.<clinit>(LendingBO.java:79)
	at biblivre.cataloging.bibliographic.BiblioRecordBO.populateDetails(BiblioRecordBO.java:94)
	at biblivre.cataloging.RecordBO.paginateSearch(RecordBO.java:233)
	at biblivre.cataloging.RecordBO.search(RecordBO.java:211)
	at biblivre.cataloging.CatalogingHandler.searchHelper(CatalogingHandler.java:112)
	at biblivre.cataloging.CatalogingHandler.search(CatalogingHandler.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at biblivre.core.controllers.Controller.processRequest(Controller.java:152)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:159)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:126)
	at biblivre.core.controllers.SchemaServlet.doPost(SchemaServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at biblivre.core.controllers.ExtendedRequestResponseFilter.doFilter(ExtendedRequestResponseFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cleydyr** [comment]
Corrigido em
5.x: #113 
cloud: #114
