### ISSUE TITLE
Property url does not exist on target class org.postgresql.ds.PGSimpleDataSource aparece nos logs

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/biblivre#162]
```
br.org.biblivre.z3950server.dao.DAOException: br.org.biblivre.z3950server.dao.DAOException: javax.naming.NamingException: Unexpected exception resolving reference [Root exception is java.lang.RuntimeException: Property url does not exist on target class org.postgresql.ds.PGSimpleDataSource]
	at br.org.biblivre.z3950server.dao.SchemasDAO.list(SchemasDAO.java:36)
	at br.org.biblivre.z3950server.Z3950ServerBO.loadCollections(Z3950ServerBO.java:97)
	at br.org.biblivre.z3950server.Z3950ServerBO.<init>(Z3950ServerBO.java:28)
	at biblivre.core.BiblivreInitializer.initialize(BiblivreInitializer.java:35)
	at biblivre.core.BiblivreContextListener.contextInitialized(BiblivreContextListener.java:33)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5641)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: br.org.biblivre.z3950server.dao.DAOException: javax.naming.NamingException: Unexpected exception resolving reference [Root exception is java.lang.RuntimeException: Property url does not exist on target class org.postgresql.ds.PGSimpleDataSource]
	at br.org.biblivre.z3950server.dao.AbstractDAO.getDataSource(AbstractDAO.java:119)
	at br.org.biblivre.z3950server.dao.AbstractDAO.getConnection(AbstractDAO.java:91)
	at br.org.biblivre.z3950server.dao.SchemasDAO.list(SchemasDAO.java:22)
	... 17 more
Caused by: javax.naming.NamingException: Unexpected exception resolving reference [Root exception is java.lang.RuntimeException: Property url does not exist on target class org.postgresql.ds.PGSimpleDataSource]
	at org.apache.naming.NamingContext.lookup(NamingContext.java:865)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:836)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:836)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:836)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:156)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at br.org.biblivre.z3950server.dao.AbstractDAO.getDataSource(AbstractDAO.java:117)
	... 19 more
Caused by: java.lang.RuntimeException: Property url does not exist on target class org.postgresql.ds.PGSimpleDataSource
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:135)
	at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
	at java.util.Hashtable.forEach(Hashtable.java:879)
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:317)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:71)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:59)
	at org.apache.naming.factory.ResourceFactory.getObjectInstance(ResourceFactory.java:141)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:848)
	... 29 more
```

**Comment by cleydyr** [comment]
5.x #163
