### ISSUE TITLE
Regressão na funcionalidade de servidor z39.50

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/biblivre#220]
Busca no próprio servidor z39.50 não funcionam

```
org.jzkit.search.SearchException: Problem With Profile Service
app_1       | 	at org.jzkit.search.impl.SearchSessionImpl.search(SearchSessionImpl.java:311)
app_1       | 	at biblivre.z3950.server.JZKitBackend.search(JZKitBackend.java:68)
app_1       | 	at org.jzkit.z3950.server.ZServerAssociation.incomingSearchRequest(ZServerAssociation.java:225)
app_1       | 	at org.jzkit.z3950.util.GenericEventToTargetListenerAdapter.update(GenericEventToTargetListenerAdapter.java:63)
app_1       | 	at java.util.Observable.notifyObservers(Observable.java:159)
app_1       | 	at org.jzkit.z3950.util.ZTargetEndpoint.notifyAPDUEvent(ZTargetEndpoint.java:211)
app_1       | 	at org.jzkit.z3950.util.ZTargetEndpoint.run(ZTargetEndpoint.java:413)
app_1       | Caused by: org.jzkit.search.util.Profile.ProfileServiceException: Unable to locate profile bath
app_1       | 	at org.jzkit.search.util.Profile.ProfileServiceImpl.makeConformant(ProfileServiceImpl.java:52)
app_1       | 	at org.jzkit.search.util.Profile.ProfileServiceImpl.makeConformant(ProfileServiceImpl.java:38)
app_1       | 	at org.jzkit.search.impl.SearchSessionImpl.search(SearchSessionImpl.java:293)
app_1       | 	... 6 more
```

**Comment by cleydyr** [comment]
master #223 
cloud #221
