### ISSUE TITLE
Bug when Search to Print Tags

### ISSUE THREAD

**Issue by lucasa** [cleydyr/biblivre#310]
Hi
I got a error when searching the registries to print tags.

2021-07-14 18:30:58,252 ERROR [http-nio-8080-exec-8] biblivre.core.exceptions.DAOException: nulljava.lang.NullPointerException: null	at biblivre.cataloging.RecordDTO.setId(RecordDTO.java:122)	at biblivre.cataloging.holding.HoldingDAO.populateDTO(HoldingDAO.java:913)	at biblivre.cataloging.holding.HoldingDAO.getSearchResults(HoldingDAO.java:892)	at biblivre.cataloging.holding.HoldingBO.paginateHoldingSearch(HoldingBO.java:285)	at biblivre.cataloging.RecordBO.paginateSearch(RecordBO.java:242)	at biblivre.cataloging.RecordBO.search(RecordBO.java:227)	at biblivre.cataloging.RecordBO.search(RecordBO.java:431)	at biblivre.cataloging.CatalogingHandler.search(CatalogingHandler.java:69)	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at biblivre.core.controllers.Controller.processRequest(Controller.java:171)	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:168)	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:127)	at biblivre.core.controllers.SchemaServlet.doPost(SchemaServlet.java:122)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at biblivre.core.controllers.ExtendedRequestResponseFilter.doFilter(ExtendedRequestResponseFilter.java:62)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)	at java.lang.Thread.run(Thread.java:748)

2021-07-14 18:30:58,253 ERROR [http-nio-8080-exec-8] biblivre.core.controllers.JsonController: error.runtime_error2021-07-14 18:30:58,253 ERROR [http-nio-8080-exec-8] biblivre.core.controllers.Controller: nulljava.lang.reflect.InvocationTargetException: null	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at biblivre.core.controllers.Controller.processRequest(Controller.java:171)	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:168)	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:127)	at biblivre.core.controllers.SchemaServlet.doPost(SchemaServlet.java:122)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at biblivre.core.controllers.ExtendedRequestResponseFilter.doFilter(ExtendedRequestResponseFilter.java:62)	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)	at java.lang.Thread.run(Thread.java:748)Caused by: biblivre.core.exceptions.DAOException: java.lang.NullPointerException	at biblivre.cataloging.holding.HoldingDAO.getSearchResults(HoldingDAO.java:897)

**Comment by cleydyr** [comment]
Hey, @lucasa . Thank you for opening this issue.

Can you provide the following information?

1. version of Biblivre you're using on your machine (did you install the oficial version or did you install one of the releases from this repository?);
2. is the behavior intermittent or does it happen consistently?
3. if the behavior happens consistently, can you provide steps to reproduce it?

**Comment by lucasa** [comment]
Hi @cleydyr!
The version is the master branch (6?) from https://github.com/cleydyr/biblivre

The error is happening all time. The log shows a null pointer.

I'm just running it inside docker. Everything else is working as usual.

Could I import the backup to another stable version?

**Comment by lucasa** [comment]
> Hey, @lucasa . Thank you for opening this issue.
> 
> Can you provide the following information?
> 
> 1. version of Biblivre you're using on your machine (did you install the oficial version or did you install one of the releases from this repository?);
> 2. is the behavior intermittent or does it happen consistently?
> 3. if the behavior happens consistently, can you provide steps to reproduce it?

Hi, Cleydyr.
Any news about 6.x version Tag prints?

**Comment by cleydyr** [comment]
Hi, @lucasa .

Should be fixed by #311 .

Thank you!
