### ISSUE TITLE
Não esta auto preenchendo campos de autoridades nem de vocabulário

### ISSUE THREAD

**Issue by Alex-Almeida** [cleydyr/biblivre#338]
Testado nas versões
Biblivre 5 (versão da instalação do site http://biblivre.org.br/) **Aqui funciona**
branch Issue-330 **Aqui tem o problema** (ultima versão que peguei)

**Problema**
Após cadastrar um registro em autoridade e outro em vocabulário, ao cadastrar uma obra não esta auto preenchendo os campos cadastrados de autoridade e vocabulário.

Como reproduzir (Autoridades):
- Acessar "Catalogação" -> "Autoridades" ;
- Clicar em "Novo registro";
- Em "Tipo de autor" selecionar "Pessoa";
- Em "Autor - Nome pessoal (100)"  -> "Sobrenome e/ou prenome do autor" digitar alguma coisa(ex: testando autor);
- Salvar a modificação;
- Ir para "Catalogação" -> "Bibliográfica";
- Clicar em "Novo registro";
- Ir até o campo "Autor - Nome pessoal (100)" e começar a digitar o que foi cadastrado em "Autoridades" (ex: testan);
- Verificar que não auto completou.

Como reproduzir (Vocabulário):
- Acessar "Catalogação" -> "Vocabulário" ;
- Clicar em "Novo registro";
- Em "TE(150)" -> "Termo tópico adotado" digitar alguma coisa(ex: testando assunto);
- Salvar a modificação;
- Ir para "Catalogação" -> "Bibliográfica";
- Clicar em "Novo registro";
- Ir até o campo "Assunto - Tópico(650)" e começar a digitar o que foi cadastrado em "Vocabulário" (ex: testan);
- Verificar que não auto completou.

**Comment by cleydyr** [comment]
Oi, @Alex-Almeida . Obrigado por abrir esse caso e por fornecer os passos para reproduzir.

Eu fiz uma modificação no branch [issue-338](https://github.com/cleydyr/biblivre/tree/issue-338). Pode dar uma olhada lá e testar?

Abraço

**Comment by Alex-Almeida** [comment]
Boa noite, baixei o branch issue-338 e está funcionando.
Mto obrigado!

**Comment by Alex-Almeida** [comment]
Opa!
Parece que tem algum problema ao restaurar backup, percebi agora usando a branch issue-338. 
Mas **não** parece ser dela o problema. Peguei a master e tbm da erro ao restaurar backup.
Na brach issue-330 o erro não ocorre usando o mesmo arquivo de backup.

A seguir tem o log e lá no final coloquei o arquivo de backup(tem apenas 1 livro cadastrado e com poucos campos) caso queira testar.
Se preferir que crie uma nova issue só avisar! Abraço
```
[Log de restauração de backup do BIBLIVRE 5]
single_schema => single_schema
Restoring 2 schemas for a total of 15943 SQL lines
Starting psql
Renaming schema single to _single_1657675063716
Renaming schema global to _global_1657675063716
Processing schema for 'global'
Processing data for 'global'
biblivre.administration.backup.exception.RestoreException: java.io.IOException: Broken pipe
	at biblivre.administration.backup.RestoreBO._writeLine(RestoreBO.java:856)
	at biblivre.administration.backup.RestoreBO.lambda$processRestore$0(RestoreBO.java:201)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:133)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at biblivre.administration.backup.RestoreBO.processRestore(RestoreBO.java:199)
	at biblivre.administration.backup.RestoreBO._processGlobalSchema(RestoreBO.java:310)
	at biblivre.administ
[backupTesteMaster.zip](https://github.com/cleydyr/biblivre/files/9098063/backupTesteMaster.zip)
ration.backup.RestoreBO.restoreBackup(RestoreBO.java:246)
	at biblivre.administration.backup.RestoreBO.restore(RestoreBO.java:135)
	at biblivre.administration.setup.Handler.restore(Handler.java:388)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at biblivre.core.controllers.Controller.processRequest(Controller.java:181)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:177)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:138)
	at biblivre.core.controllers.SchemaServlet.doPost(SchemaServlet.java:133)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at biblivre.core.controllers.ExtendedRequestResponseFilter.doFilter(ExtendedRequestResponseFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.io.IOException: Stream closed
		at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
		at java.base/java.io.OutputStream.write(OutputStream.java:162)
		at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
		at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
		at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304)
		at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
		at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
		at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
		at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
		at java.base/java.io.BufferedWriter.close(BufferedWriter.java:268)
		at biblivre.administration.backup.RestoreBO.restoreBackup(RestoreBO.java:237)
		... 37 more
Caused by: java.io.IOException: Broken pipe
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
	at java.base/java.io.Writer.write(Writer.java:249)
	at biblivre.administration.backup.RestoreBO._writeLine(RestoreBO.java:853)
	... 52 more
```
[backupTesteMaster.zip](https://github.com/cleydyr/biblivre/files/9098066/backupTesteMaster.zip)

**Comment by cleydyr** [comment]
Oi, @Alex-Almeida. Obrigado por confirmar que o problema original está resolvido.

Esse novo problema deverá ser tratado em uma nova _issue_ para não misturar temas e facilitar a busca por informação. Você pode abri-la para mim por gentileza?

Abraço
